In [1]:
import numpy as np
a=100,2,87,9,9,6,4
np.array(a)
type(a)
np.ndim(a)

1

In [2]:
c=np.array([[4,5,6],[1,2,3]])
np.ndim(c)

2

In [3]:
aa=10
import numpy as np
array=np.array(aa)
type(array)
np.ndim(aa)

0

In [4]:
dd=np.array([[1,2,3],[4,5,6]])
np.ndim(dd)

2

In [5]:
tt=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
np.ndim(tt)

3

In [6]:
a=np.array([[1,2,3,4],[1,23,4,6]])
a.size

8

In [7]:
a.shape

(2, 4)

In [8]:
a.dtype

dtype('int64')

In [9]:
n=np.arange(1,100,2)
n

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [10]:
n=n.astype("float")
n

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [11]:

v=np.array([[[ 1,  2,  3],[ 4,  5,  6]],[[ 1,  2,  3],[ 9, 10, 11]]])
v


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 9, 10, 11]]])

In [12]:
np.ndim(v)


3

In [13]:
#array properties
#ndim
#shape
#size
#dtype

In [14]:
v.shape


(2, 2, 3)

In [15]:
v.dtype

dtype('int64')

In [16]:
v.size

12

In [19]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [21]:
mat=np.arange(1,37)
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [24]:
mat=mat.reshape(6,6)
mat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [26]:
mat[1:4,2:5]

array([[ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])

In [28]:
def fun(l):
    return l*5
l=[1,2,3,4,5]
m=list(map(fun,l))
m

[5, 10, 15, 20, 25]

In [30]:
la=np.array(l)
print(la*5)

[ 5 10 15 20 25]


In [36]:
a=[1,2,3]
print(a)
b=[[4],[5],[6]]
print(b)
c=a+b


[1, 2, 3]
[[4], [5], [6]]


In [34]:
np.ndim(a)

1

In [37]:
np.ndim(b)

2

In [43]:
np.sum(b)

np.int64(15)

In [45]:
np.max(b)

np.int64(6)

In [46]:
np.min(b)

np.int64(4)

In [50]:
np.mean(a)

np.float64(2.0)

In [51]:
np.median(a)

np.float64(2.0)

In [52]:
np.log(b)

array([[1.38629436],
       [1.60943791],
       [1.79175947]])

In [53]:
np.sqrt(b)

array([[2.        ],
       [2.23606798],
       [2.44948974]])

In [56]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [55]:
np.std(a)

np.float64(0.816496580927726)

In [57]:
np.dot(a,b)

array([32])

In [61]:
np.dot(a,b)

array([32])

In [64]:
np.random.rand(4,4)

array([[0.33509749, 0.09773594, 0.4866358 , 0.12036463],
       [0.85077795, 0.05406983, 0.53501529, 0.85525702],
       [0.85612012, 0.22162305, 0.34492391, 0.46611645],
       [0.03150796, 0.02231941, 0.45703257, 0.78713065]])

In [68]:
np.random.randint(1,1000,6)

array([ 40, 161, 848, 179, 720, 599], dtype=int32)

In [69]:
np.random.normal(8,2,100)#mean.std.size

array([ 7.51725992,  8.50552092,  9.39225711,  9.24925719,  7.09228087,
        7.71674333,  5.75056828,  9.70361516,  7.8544011 ,  7.59788879,
        5.98582347,  4.88451458,  9.21809831,  6.81789518,  5.62955695,
        9.7408562 ,  6.40121169,  7.08716935,  9.38052392,  6.20724987,
        7.53877622, 10.1837204 ,  9.63670821,  9.38642754,  7.07700196,
        8.30282379, 10.33468406,  7.64113665,  6.09672472, 10.50451693,
       11.59716018,  7.88687434,  7.24282714,  2.76303383,  5.78174284,
        7.54498548,  7.33379038,  8.13295055,  9.27443983,  6.72101968,
        9.30175664,  8.27468071, 10.15386949,  7.18772669,  6.73398007,
        4.24018789,  6.45091909,  4.5789646 , 10.79695388,  6.83678163,
        7.44629291,  5.0526935 ,  7.65568003,  6.17519687, 10.2516464 ,
       10.14571177, 10.02379497,  8.90167115,  9.92944174,  0.74771317,
        8.79636197,  8.18017465,  6.33078356,  8.4865959 , 11.41699828,
        7.08785265,  7.15496299,  8.52605463,  7.64757089, 10.31

In [71]:
ans=np.array([7.51725992,  8.50552092,  9.39225711,  9.24925719,  7.09228087,
        7.71674333,  5.75056828,  9.70361516,  7.8544011 ,  7.59788879,
        5.98582347,  4.88451458,  9.21809831,  6.81789518,  5.62955695,
        9.7408562 ,  6.40121169,  7.08716935,  9.38052392,  6.20724987,
        7.53877622, 10.1837204 ,  9.63670821,  9.38642754,  7.07700196,
        8.30282379, 10.33468406,  7.64113665,  6.09672472, 10.50451693,
       11.59716018,  7.88687434,  7.24282714,  2.76303383,  5.78174284,
        7.54498548,  7.33379038,  8.13295055,  9.27443983,  6.72101968,
        9.30175664,  8.27468071, 10.15386949,  7.18772669,  6.73398007,
        4.24018789,  6.45091909,  4.5789646 , 10.79695388,  6.83678163,
        7.44629291,  5.0526935 ,  7.65568003,  6.17519687, 10.2516464 ,
       10.14571177, 10.02379497,  8.90167115,  9.92944174,  0.74771317,
        8.79636197,  8.18017465,  6.33078356,  8.4865959 , 11.41699828,
        7.08785265,  7.15496299,  8.52605463,  7.64757089, 10.31352312,
       10.49656193,  9.79332802,  8.86268617,  6.35265309,  6.57916653,
        9.21002471,  9.01095405,  9.15108676,  5.20231834,  5.97090761,
        6.50331015,  7.58924371,  8.7199747 ,  6.08733522,  4.71322635,
       11.75444485,  7.80491944,  9.11063539,  7.48472097,  7.81127641,
        6.51272826,  8.81872719,  6.81875994,  8.55401717,  8.20283605,
        9.14980737,  6.82701979,  8.33115192,  5.77380775,  7.18110958])

In [72]:
np.mean(ans)

np.float64(7.8191931818)

In [73]:
np.std(ans)

np.float64(1.8661855080144982)

In [74]:
c

[1, 2, 3, [4], [5], [6]]

In [77]:
c=np.array([[5,6,7],[6,7,8],[7,8,9]])

In [78]:
c


array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [79]:
c>7


array([[False, False, False],
       [False, False,  True],
       [False,  True,  True]])

In [81]:
print(c.reshape(-1,1))
print(c.reshape(1,-1))

[[5]
 [6]
 [7]
 [6]
 [7]
 [8]
 [7]
 [8]
 [9]]
[[5 6 7 6 7 8 7 8 9]]


In [83]:
c.flatten()

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [85]:
c.ravel()

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [88]:
np.vstack(c)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [89]:
np.hstack(c)

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [90]:
np.sort(c)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [93]:
np.hsplit(c,3)

[array([[5],
        [6],
        [7]]),
 array([[6],
        [7],
        [8]]),
 array([[7],
        [8],
        [9]])]

In [95]:
np.vsplit(c,3)

[array([[5, 6, 7]]), array([[6, 7, 8]]), array([[7, 8, 9]])]

In [96]:
np.sum(c,axis=0)

array([18, 21, 24])

In [97]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])