In [1]:
import pandas as pd

In [2]:
d=pd.read_csv("golf_df.csv")
d

,Outlook,Temperature,Humidity,Windy,Play
0,sunny,hot,high,False,no
1,sunny,hot,high,True,no
2,overcast,hot,high,False,yes
3,rainy,mild,high,False,yes
4,rainy,cool,normal,False,yes
5,rainy,cool,normal,True,no
6,overcast,cool,normal,True,yes
7,sunny,mild,high,False,no
8,sunny,cool,normal,False,yes
9,rainy,mild,normal,False,yes


In [3]:
d.columns

Index(['Outlook', 'Temperature', 'Humidity', 'Windy', 'Play'], dtype='object')

In [4]:
x=d[["Outlook"]]
y=d["Play"]

In [5]:
x

,Outlook
0,sunny
1,sunny
2,overcast
3,rainy
4,rainy
5,rainy
6,overcast
7,sunny
8,sunny
9,rainy


In [6]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le=LabelEncoder()
x1=le.fit_transform(x)
x1=x1.reshape(-1,1)
x1

C:\Users\ELCOT\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[2],
       [2],
       [0],
       [1],
       [1],
       [1],
       [0],
       [2],
       [2],
       [1],
       [2],
       [0],
       [0],
       [1]])

In [19]:
le=LabelEncoder()
y1=le.fit_transform(y)
y1

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [20]:
from sklearn.naive_bayes import CategoricalNB

In [23]:
model=CategoricalNB()
model.fit(x1,y1)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None
,min_categories,None


In [26]:
model.predict([[0]])

array([1])